name: koa_app
description: Aplicación neuroinclusiva para niños con neurodivergencias

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  firebase_analytics: ^10.7.3
  
  mercado_pago_sdk: ^2.1.0
  url_launcher: ^6.2.0
  http: ^1.1.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.1
  share_plus: ^7.2.1  # Para compartir PDFs
  path: ^1.8.3  # Para manejar rutas de archivos
  # Estado y Arquitectura
  provider: ^6.1.1
  riverpod: ^2.4.9
  
  # UI y Diseño
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
  
  # Navegación
  go_router: ^12.1.3
  animated_splash_screen: ^1.3.0
  
  # Offline
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.1
  synchronized: ^3.1.0
  
  # PDF y Exportación
  pdf: ^3.10.2
  printing: ^5.11.1
  path_provider: ^2.1.1
  
  # Accesibilidad
  flutter_tts: ^3.8.3
  speech_to_text: ^6.6.0
  
  # Pagos
  mercado_pago_sdk: ^2.1.0
  
  # IA
  http: ^1.1.0
  tensorflow_lite_flutter: ^3.0.0
  
  # Utilidades
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/fonts/
    
  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700