name: koa_app
description: Aplicación neuroinclusiva para niños con neurodivergencias

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 🔥 FIREBASE
  firebase_core: ^2.27.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  firebase_analytics: ^10.10.0

  # 🔥 ESTADO Y ARQUITECTURA
  provider: ^6.1.2

  # 🔥 UI Y DISEÑO
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  # IA 
  tflite_flutter: ^0.11.0
  google_generative_ai: ^0.4.7

  # 🔥 NAVEGACIÓN
  go_router: ^14.1.2

  # 🔥 PAGOS - ACTUALIZADO
  flutter_custom_tabs: ^2.4.0
  http: ^1.2.1

  # 🔥 UTILIDADES
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  package_info_plus: ^9.0.0
  share_plus: ^7.2.2

  # 🔥 OFFLINE Y ALMACENAMIENTO
  sqflite: ^2.3.3+1
  connectivity_plus: ^6.0.2
  synchronized: ^3.1.0
  path_provider: ^2.1.3
  path: ^1.9.0

  # 🔥 ACCESIBILIDAD
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.0

  # 🔥 PDF
  pdf: ^3.10.8
  printing: ^5.12.0

  # 🔥 NOTIFICACIONES
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700