// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR5mAYVTSK81w_U1UTrEdXACUu0UVBdOc',
    appId: '1:1078432165839:web:f74e728d7aafda8b40acba',
    messagingSenderId: '1078432165839',
    projectId: 'koa-project-6a0ff',
    authDomain: 'koa-project-6a0ff.firebaseapp.com',
    storageBucket: 'koa-project-6a0ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxqHiqp7He2R_26HWw60U9mUA-gKLc3g',
    appId: '1:1078432165839:android:e8e0fa599596c56140acba',
    messagingSenderId: '1078432165839',
    projectId: 'koa-project-6a0ff',
    storageBucket: 'koa-project-6a0ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_61AflYZFnkqSjtYzwecbsiOAF3mwiEI',
    appId: '1:1078432165839:ios:60b9a902867afcea40acba',
    messagingSenderId: '1078432165839',
    projectId: 'koa-project-6a0ff',
    storageBucket: 'koa-project-6a0ff.firebasestorage.app',
    iosBundleId: 'com.example.koaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_61AflYZFnkqSjtYzwecbsiOAF3mwiEI',
    appId: '1:1078432165839:ios:60b9a902867afcea40acba',
    messagingSenderId: '1078432165839',
    projectId: 'koa-project-6a0ff',
    storageBucket: 'koa-project-6a0ff.firebasestorage.app',
    iosBundleId: 'com.example.koaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR5mAYVTSK81w_U1UTrEdXACUu0UVBdOc',
    appId: '1:1078432165839:web:68d77eea08bb1f6940acba',
    messagingSenderId: '1078432165839',
    projectId: 'koa-project-6a0ff',
    authDomain: 'koa-project-6a0ff.firebaseapp.com',
    storageBucket: 'koa-project-6a0ff.firebasestorage.app',
  );
}
